<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>CathVision.Cube.Recorder.WpfUtilities</RootNamespace>
    <UseWPF>True</UseWPF>
  </PropertyGroup>

  <PropertyGroup>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>1573;1591</NoWarn>
  </PropertyGroup>

</Project>
